### ISSUE TITLE
Node Server Deployment giving Error

### ISSUE THREAD

**Issue by ciarapowell** [UF-COP5035/Rater-System#26]
When I try to run on dev folder I get error:

PS C:\Users\Ciara\Rater-System> node server
module.js:471
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Ciara\Rater-System\server\routes\api.js:8:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

It seems like my branches are running fine on localhost 3000.
@ltcarbonell  Can you see if the heroku deployment is causing this issue?

**Comment by ltcarbonell** [comment]
For this to be resolved include the .env file provided in slack to your root folder. Without it you will not have access to the remote development database

**Comment by ltcarbonell** [comment]
For this to be resolved include the .env file provided in slack to your root folder. Without it you will not have access to the remote development database.  If @christopher1030123 @ciarapowell @rahulp94 if any of you need the file resent to you please let me know.  Keep in mind the file name must be `.env` including the . in the beginning.

In addition you must have the `dotenv` module included in your `package.json` .  Once you have confirmed it is in there run `npm install && ng build`.  Then to launch the server run `node server` and go to localhost:3000

**Comment by christopher1030123** [comment]
I may need this .env file

Luis (LT) Carbonell <notifications@github.com>于2017年9月27日 周三下午8:57写道：

**Comment by ciarapowell** [comment]
Thanks for the instructions. Worked beautifully

**Comment by ltcarbonell** [comment]
![Alt Text](http://media.tumblr.com/tumblr_ma7kq8A0LA1rsw1yf.gif)
