### ISSUE TITLE
Update the landing page to include a login

### ISSUE THREAD

**Issue by ltcarbonell** [UF-COP5035/Rater-System#34]
There should be three different login options when logging in.  One for students, one for teachers and one for administration.

Each will use the service for the respective user type, call that services getUsertypeByUsername() method to determine that is a valid user and, if so, set user as active user and proceed to /usertype. 

For example, for students:
The student will log in with their username, which is checked against getStudentByUsername(), if a valid student user, the active user is set to this user and the new page website.com/students will be loaded. The implementation of how the active user is stored is not as important, the purpose of this ticket is to make sure a valid user is redirected to the correct url route.

This can be started at anytime, but will need to have #46, #49, and #50 complete prior to completion.

This does **NOT** include authentication at this point.  That will be added at a later date.  A simple username check will suffice.

**Comment by ciarapowell** [comment]
Hey, I am kinda stuck. I am trying to send the username to the function login, call the get...username to get a user with a specific username, get id from user and then route to specific dashboard. 
Any Idea of what I am doing wrong or a better way of doing this? 

`import { Component, OnInit, Injectable } from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import { Headers, Http } from '@angular/http';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { AdministratorService } from '../administrator/administrator.service';
import { TeacherService } from '../teacher/teacher.service';
import { StudentService } from '../student/student.service';
import { Administrator } from '../administrator/administrator';
import { Teacher} from '../teacher/teacher';
import { Student } from '../student/student';


import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/toPromise';


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  hide = true;
  students: Student[] = [];
  teachers: Teacher;
  administrators: Administrator[] = [];

  constructor(private teacherService: TeacherService,
    private administratorService: AdministratorService,
    private studentService: StudentService,
    private router: Router
) { }

  ngOnInit() {
  }

  login(userType: string, userName: string ){

    if(userType == 'teacher'){
      this.teacherService. getTeacherUsername(userName).then(teachers => this.teachers) ;
      if(this.teachers == null){
      console.log('Cool');
      }
      else {
        let teacherId = this.teachers._id;
        this.router.navigate(['/teacher-dashboard', { id: teacherId}])
      }
    }
    if(userType == 'student'){

    }
    if(userType == 'administrator'){

    }

  }


}
`

**Comment by ciarapowell** [comment]
I have confirmed that the userType if statement is okay. I am just hung up on what service to call to check username....

**Comment by ltcarbonell** [comment]
@ciarapowell 
We slightly changed the services to search by ID not username.  The user name search is being added in #68.  For now the search would have to be by Object ID.
