### ISSUE TITLE
Create queries for Student / Teacher relationships

### ISSUE THREAD

**Issue by ciarapowell** [UF-COP5035/Rater-System#78]
Create queries for Student / Teacher relationships
For reviews, I would like to be able to get a list of students for each teacher and a list of teachers for each student. 
I think the courses database could include this information, but I am open to another option.

**Comment by ltcarbonell** [comment]
Ok. I can wrap this into my other service functions I am making. 

The student service will have a method called getTeachers and Teacher service will have one called getStudents

If there are more you need comment and and them here as they come up.

**Comment by ciarapowell** [comment]
I was wondering where courses would come into play ?  Maybe teachers can view students by course

**Comment by ltcarbonell** [comment]
These are the service methods I will be making as part of this ticket.  The other crud services will be in their own separate ticket (#68) since they are already done

Student services
``` ts
getTeachersByStudent(student_id)  // Returns an array of teachers this student has
getCoursesByStudent(student_id)  // Returns an array of the courses this student is taking
getReviewsByStudent(student_id)  // Returns an array of review this student is associated with
```
Teacher services
``` ts
getStudentsByTeacher(teacher_id)  // Returns an array of students this teacher has
getCoursesByTeacher(teacher_id)  // Returns an array of the courses this teacher is teaching
getReviewsByTeacher(teacher_id)  // Returns an array of review this teacher is associated with
```
Administrator services
``` ts
// Students, courses and reviews are determined by the teachers this admin is in charge of
getTeachersByAdministrator(admin_id)  // Returns an array of teachers this administrator is in charge of
getStudentsByAdministrator(admin_id)  // Returns an array of students this administrator is in charge of
getCoursesByAdministrator(admin_id)  // Returns an array of the courses this administrator is teaching
getReviewsByAdministrator(admin_id)  // Returns an array of review this administrator is associated with
```

**Comment by ltcarbonell** [comment]
This is all I could think of for right now.  Let me know if you think of anymore

**Comment by ltcarbonell** [comment]
Any new services that need to be created should be included in a new ticket
